apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo_project
  annotations:
    github.com/project-slug: swatigarg93/demo_project
spec:
  type: other
  lifecycle: unknown
  owner: user:swatigarg93
